#!/bin/bash

# ========================================
# 🚀 SMART HOME DASHBOARD - RUN GUIDE
# ========================================
# 
# This script shows the exact commands to run
# Copy and paste each command into separate terminals

echo "=========================================="
echo "🚀 SMART HOME DASHBOARD - QUICK START"
echo "=========================================="
echo ""

# ========== TERMINAL 1 ==========
echo "📱 TERMINAL 1 - START BACKEND API"
echo "=========================================="
echo ""
echo "Copy and paste this command:"
echo ""
echo "    cd /home/pavluk/RiderProjects/System-Inteligentnego-Biura/SmartHomeAPI"
echo "    dotnet run"
echo ""
echo "Expected output:"
echo "    info: Microsoft.Hosting.Lifetime[14]"
echo "          Now listening on: http://127.0.0.1:5047"
echo ""
echo "⚠️  KEEP THIS TERMINAL RUNNING!"
echo ""
echo ""

# ========== TERMINAL 2 / BROWSER ==========
echo "🌐 TERMINAL 2 / BROWSER - OPEN FRONTEND"
echo "=========================================="
echo ""
echo "Option A: Direct File (recommended)"
echo "-----------------------------------"
echo "Copy and paste into your browser address bar:"
echo ""
echo "    file:///home/pavluk/RiderProjects/System-Inteligentnego-Biura/SmartHomeAPI/frontend/index.html"
echo ""
echo ""
echo "Option B: Using HTTP Server"
echo "----------------------------"
echo "Copy and paste this command in a new terminal:"
echo ""
echo "    cd /home/pavluk/RiderProjects/System-Inteligentnego-Biura/SmartHomeAPI/frontend"
echo "    python3 -m http.server 8000"
echo ""
echo "Then open in browser:"
echo ""
echo "    http://localhost:8000/index.html"
echo ""
echo ""

# ========== TERMINAL 3 ==========
echo "🧪 TERMINAL 3 - ADD TEST DATA (optional)"
echo "=========================================="
echo ""
echo "1️⃣  Create Temperature Sensor:"
echo "---"
echo "    curl -X POST http://localhost:5047/api/sensors \\"
echo "      -H \"Content-Type: application/json\" \\"
echo "      -d '{\"name\":\"Living Room Temp\",\"type\":\"Temperature\",\"roomId\":1}'"
echo ""
echo ""
echo "2️⃣  Create Humidity Sensor:"
echo "---"
echo "    curl -X POST http://localhost:5047/api/sensors \\"
echo "      -H \"Content-Type: application/json\" \\"
echo "      -d '{\"name\":\"Living Room Humidity\",\"type\":\"Humidity\",\"roomId\":1}'"
echo ""
echo ""
echo "3️⃣  Send Temperature Reading (Sensor ID should be 1):"
echo "---"
echo "    curl -X POST http://localhost:5047/api/sensor-data \\"
echo "      -H \"Content-Type: application/json\" \\"
echo "      -d '{\"sensorId\":1,\"type\":\"Temperature\",\"value\":22.5}'"
echo ""
echo ""
echo "4️⃣  Send Humidity Reading (Sensor ID should be 2):"
echo "---"
echo "    curl -X POST http://localhost:5047/api/sensor-data \\"
echo "      -H \"Content-Type: application/json\" \\"
echo "      -d '{\"sensorId\":2,\"type\":\"Humidity\",\"value\":55}'"
echo ""
echo ""
echo "✅ After each command, the dashboard will update automatically!"
echo ""
echo ""

# ========== USAGE ==========
echo "💡 HOW TO USE THE DASHBOARD"
echo "=========================================="
echo ""
echo "1. Sensors appear as cards with:"
echo "   - Sensor name"
echo "   - Latest reading with units (°C, %, ppm, etc.)"
echo "   - Status: 'OK' or 'ALARM' (in red)"
echo "   - 'Pokaż wykres' button"
echo ""
echo "2. Click 'Pokaż wykres' on any sensor to see:"
echo "   - Line chart of recent readings"
echo "   - Timestamps"
echo "   - Sensor type and units"
echo ""
echo "3. Use 'Dodaj nowy czujnik' form to:"
echo "   - Add new sensors to the system"
echo "   - Select type from dropdown"
echo "   - Enter room ID"
echo ""
echo "4. Use 'Wyślij odczyt czujnika' form to:"
echo "   - Send sensor readings"
echo "   - Choose sensor ID and type"
echo "   - Enter the value"
echo ""
echo "5. Dashboard auto-refreshes:"
echo "   - Every 30 seconds"
echo "   - No page refresh needed"
echo ""
echo ""

# ========== ALARM THRESHOLDS ==========
echo "🚨 ALARM THRESHOLDS"
echo "=========================================="
echo ""
echo "Sensor Type        | Threshold"
echo "-------------------+-----------"
echo "Temperature        | > 30°C (shows ALARM in red)"
echo "Humidity           | > 70% (shows ALARM in red)"
echo "CO₂                | > 1000 ppm (shows ALARM in red)"
echo "Smoke              | > 0 (any detection = ALARM)"
echo "Motion             | > 0 (any detection = ALARM)"
echo "Light              | No alarm (always OK)"
echo ""
echo ""

# ========== TROUBLESHOOTING ==========
echo "🐛 TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "Q: 'Błąd połączenia' (Connection Error)"
echo "A: Check that 'dotnet run' is working in Terminal 1"
echo ""
echo "Q: No sensors appearing"
echo "A: Add sensors using curl commands or the 'Dodaj nowy czujnik' form"
echo ""
echo "Q: Chart not showing"
echo "A: Send at least one reading, then click 'Pokaż wykres'"
echo ""
echo "Q: How do I know which sensor ID to use?"
echo "A: Check the response from the 'create sensor' curl command"
echo "   First sensor will be ID 1, second will be ID 2, etc."
echo ""
echo ""

# ========== FILE LOCATIONS ==========
echo "📁 FILE LOCATIONS"
echo "=========================================="
echo ""
echo "Backend:"
echo "  /home/pavluk/RiderProjects/System-Inteligentnego-Biura/SmartHomeAPI/Program.cs"
echo ""
echo "Frontend:"
echo "  /home/pavluk/RiderProjects/System-Inteligentnego-Biura/SmartHomeAPI/frontend/index.html"
echo "  /home/pavluk/RiderProjects/System-Inteligentnego-Biura/SmartHomeAPI/frontend/app.js"
echo "  /home/pavluk/RiderProjects/System-Inteligentnego-Biura/SmartHomeAPI/frontend/style.css"
echo ""
echo "Database:"
echo "  /home/pavluk/RiderProjects/System-Inteligentnego-Biura/SmartHomeAPI/smarthome.db"
echo ""
echo ""

# ========== SUMMARY ==========
echo "✅ SUMMARY"
echo "=========================================="
echo ""
echo "✓ Backend is ready (C# .NET 10)"
echo "✓ Frontend is ready (HTML/CSS/JS)"
echo "✓ CORS is configured"
echo "✓ Database is ready"
echo "✓ All forms are functional"
echo "✓ Charts are implemented"
echo "✓ Auto-refresh is enabled"
echo ""
echo "👉 Ready to run! Follow the 3 terminal setup above."
echo ""
echo "=========================================="

